compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: /home/zb/NlpTaskSpace-llm/config/deepspeed/zero_stage3_config.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: "no"
dynamo_backend: "NO"
fsdp_config: {}
main_process_ip: null
main_process_port: 29503
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false
