compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: /home/zb/NlpTaskSpace-llm/config/deepspeed/zero_stage2_config.json
  zero3_init_flag: false
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: 29501
main_training_function: main
num_machines: 1
num_processes: 2
use_cpu: false
